import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavigationBar from "@/components/NavigationBar";
import {
    FloatingDockDemo
} from "@/components/SocialBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("antialiased bg-white dark:bg-black", inter.className)}
      >
        <NavigationBar />
        <main className="mt-[64px]"> {/* Adjust the margin-top value based on your navbar height */}
          {children}

        </main>



      </body>
    </html>
  );
}
